backend:
  name: git-gateway
  branch: main # Cambia si tu rama principal se llama 'master'

# Esta configuración es importante para el Decap CMS
publish_mode: editorial_workflow

# Carpeta donde se guardan las imágenes subidas
media_folder: "static/uploads"
public_folder: "/static/uploads"

# Colección principal de contenido: Historias
collections:
  - name: "historias"
    label: "Historias"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Cuerpo del Cuento", name: "body", widget: "markdown"}